### ISSUE TITLE
Add Scholarship form CTA to site

### ISSUE THREAD

**Issue by JeffLowe** [techlahoma/thunderplains-2019#16]
Link to 2019 form
https://docs.google.com/forms/d/e/1FAIpQLScuixTHNMHiLIMyw0OG7cvpYtrKw7LryiP0IHtWg8mmS6GpaQ/viewform?usp=sf_link

May just put it as a CTA link alongside the volunteer CTA.

**Comment by DevinClark** [comment]
Done
