### ISSUE TITLE
Need Speaker Images and Bios

### ISSUE THREAD

**Issue by vlucas** [techlahoma/thunderplains-2019#20]
These not being on the site is potentially impacting ticket sales... They should have been on the site long ago...

**Comment by kacollins** [comment]
Is this something that new people could help with for Hacktoberfest? Where are the images and bios stored? What about talk descriptions?

**Comment by vlucas** [comment]
I don't know. @carmalou was in charge of speaker communications this year. We can get them, but I guess maybe it's too late now...

**Comment by DevinClark** [comment]
They are in papercall.

**Comment by kacollins** [comment]
I personally would appreciate talk descriptions, if they are available, for choosing which ones to attend. If they are easily accessible, I bet we could get some help with adding them to the website.

**Comment by kacollins** [comment]
It doesn't look like I have access to papercall.

**Comment by vlucas** [comment]
@DevinClark Can you update the site?

**Comment by vlucas** [comment]
We typically have this already done way in advance, and I think it has probably impacted ticket sales
